"""empty message

Revision ID: cec62a2f0173
Revises: 1f3746565ff5
Create Date: 2021-01-31 12:10:47.657198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cec62a2f0173'
down_revision = '1f3746565ff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows_relation', sa.Column('start_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows_relation', 'start_date')
    # ### end Alembic commands ###
